version: '3.8'

services:
  flask-api:
    build:
      context: ./flask-api
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/instance/cms_blog.db
    volumes:
      - flask-data:/app/instance
    restart: unless-stopped
    networks:
      - blog-cms-network

  react-app:
    build:
      context: ./react-login
    expose:
      - "3000"
    depends_on:
      - flask-api
    restart: unless-stopped
    networks:
      - blog-cms-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/blog-cms.template:/etc/nginx/conf.d/default.conf.template
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    depends_on:
      - react-app
      - flask-api
    restart: unless-stopped
    networks:
      - blog-cms-network
    command: >
      sh -c "envsubst '$$DOMAIN_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && 
             nginx -g 'daemon off;'"

networks:
  blog-cms-network:
    driver: bridge

volumes:
  flask-data:
    driver: local